version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: strong-xml
    versions:
    - 0.6.0
    - 0.6.1
  - dependency-name: env_logger
    versions:
    - 0.8.2
